pipeline:
  install:
    image: node:10.1.0
    commands:
      - node -v
      - npm -v
  test:
    image: node:10.1.0
    group: testing
    commands:
      - npm install -g mocha
      - npm test
  publish:
    image: plugins/docker
    repo: quexten/sso-api
    tags: latest
    secrets: [ docker_username, docker_password ]
  notify:
    image: plugins/slack
    webhook: https://discordapp.com/api/webhooks/463932643856351242/Tui74Bn2F2JAWr6dGOn2DY3cpwTexf8EWi2VEzhRsm5Fm8BTC7YGh5XsHo4kx4Wm8fZk/slack
    channel: sso-api
