pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
     - ./node_modules
     - ./yarn.lock
    volumes:
      - /tmp/cache:/cache

  install:
    image: node:10.1.0
    commands:
      - yarn install
      - node -v
      - npm -v
      - yarn -v

  test:
    image: node:10.1.0
    group: testing
    commands:
      - yarn test

  publish:
    image: plugins/docker
    repo: quexten/sso-api
    tags: latest
    secrets: [ docker_username, docker_password ]

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
      - ./yarn.lock
    volumes:
      - /tmp/cache:/cache

  notify-discord:
    image: appleboy/drone-discord:1.0.0
    webhook_id: 463932643856351242
    webhook_token: Tui74Bn2F2JAWr6dGOn2DY3cpwTexf8EWi2VEzhRsm5Fm8BTC7YGh5XsHo4kx4Wm8fZk
    when:
      status: [ success, failure ]
  
  notify-telegram-fail:
    image: appleboy/drone-telegram
    token: 676321391:AAFWtrvlqju_8um3ur8gDP16EHJmzPtFQyU
    to: quexten_builds
    message:
      Build {{build.number}} succeded.
    when:
      status: [ failure ]

  notify-telegrame-success:
    image: appleboy/drone-telegram
    token: 686461508:AAEaWghtYF8eE2ve6_TsPj46aZwbxKC5v-8
    to: quexten_builds
    message:
      Build {{build.number}} failed.
    when:
      status: [ success ]    
