version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
           - ./node_modules
  publish:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ~/repo
      - run: docker login --username $docker_username --password $docker_password
      - run: docker build -t quexten/sso-api:latest .
      - run: docker push quexten/sso-api:latest
      - run: curl https://cdn.wedeploy.com/cli/latest/wedeploy.sh -fsSL | bash

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - deploy:
         requires:
          - build
         filters:
           branches:
             only: release




